
sub blok_n2 ()

    call SEL0 ()
    ' call grup_cor ( "node","sel","na>12|na<11","1")
    ' kor "11269 12134 12134 12126 12126 8333 15174" , "sel=0"
    ' call rastr.ekv ("")
    call grup_cor ( "node","sel","na>11|na<11|na=0","1")
    kor "15174 16102 16095" , "sel=0"
    kor "15501 15502 20001" , "sel=1"

    call rastr.ekv ("")
    call SEL0 ()
    kor "20001,16095,0 20001,16102,0" , "r=1 x=1"    
    kor "15007" , "pg=0 qg=0 pn=0 qn=0 qmax=0 qmin=0 vzd=0 bsh=0"        
    kor "15205" , "pg=0 qg=0 pn=0 qn=0 qmax=-100 qmin=-5 vzd=235 bsh=0"        
    kor "g,80014 g,80018" , "sel=1"        
    call Del_sel ()


    call RGM_kor ("режим не сбалансирован blok_n")
end sub 

sub ImpRg22 ()' запуск ИД для импорта'---------ИМПОРТ из модели-------------
    ' set ImportClass = new import_class '  обн прис 
    ' ImportClass.uslovie_start = array ("","","","")
    ' ImportClass.import_File = "I:\ОЭС Юга\КПР КУБАНИ\модели\sel уд гр айди.rg2"
    ' ImportClass.tabl = "vetv" 
    ' ImportClass.param = array("groupid","") ' "node;vetv;Generator", ("пусто-все или перечислить","набор парам")параметры так же можно ";"
    ' ImportClass.vibor = "sel" 
    ' ImportClass.tip   = "2" '"2" обн, "1" заг, "0" прис, "3" обн-прис
    ' call GLK.dictImpRg2.Add  (ImportClass.import_File & cstr(round(Rnd,4)*10000), ImportClass)       
    
end sub 
sub blok_k2 ()

    call SEL0 ()
    call Del_sel ()

    call RGM_kor ("режим не сбалансирован blok_k")
end sub 
    '<<<<<<<<<<<<<<<<<<<<СПРАВКА>>>>>>>>>>>>>>>>>>>>>>>>>
        '<<<ДОБАВИТЬ>>>
    ' =fTAB_str_add ( "ngroup" , "nga=15" ) ' добавить запись в таблицу и вернуть indx ( "vetv" , "ip=1 iq=2 np=10 i_dop=100" )
    ' =fVetv_add_ndx (dname , ip , iq , np , r , x , b) ' добавить ветвь и вернуть indx
    ' =fNode_add (name , na , npa , uhom,ny)            ' добавить узел и вернуть номер (ny или 0)
    ' call vetv_vikl_add (viborka) ' для ветвей добавить выкл в начале и в конце
    ' call node_ku_add (viborka) ' к узлам присоединить новый узел и перенести ШР БСК УШР
    ' call sel_ssh2_add ()       ' к отмеченным узлам присоединить новый узел через выключатель и перенести верви с np=2,4,6 - мб не последняя версия
    ' call groupid_sel_sub ()' 0 нет 1 задать groupid отмеченных узлов ()
        '<<<УДАЛИТЬ>>>
    ' call Del_sel ()            ' удалить отмеченные узлы (c ветвями) ветви и генераторы
    ' call Del(tabl,viborka)  'viborka = "net" - удалить узлы или ветви без связей или без узла начала конца
        '<<<ИЗМЕНИТЬ СЕТЬ>>>
    'call SEL0 ()                    ' снять выделение узлов и ветвей  и генераторов
    'call SEL ("zadanie" , no_off) ' отметить, например "123 123,312,1 g,12",  no_off = 0 снять отметку 1 отметить	
    'call kor  ("kkluch" , "zadanie")' коррекция , например  kor "125 25" , "pn=10.2 qn=5.4" для узла, "g,125 g,125" , "Pmax=10 " для ген , "1,2,0 12,125,1" , "r=10.2 x=1" для ветви , также есть no npa na nga (принцип grup_cor)
    'call kor1  (k_kluch , param_kor , value_param)' коррекция одного уникальнгого занчения(краткийй ключ, параметр корр, значение) например("7","name","Юж")
    'call grup_cor ( "tabl","param","viborka","formula")' групповая коррекция "node","bsh","ny=87",-3036/1000000
    'call sta_node ("str_ny", on_off)' узлы с ветвями (СТРОКА номера узлов через пробел) включить false; отключить true 
    'call tN.cols("qn").calc ("0") 
    'Rastr.RenumWP=True     'включить ссылки, отключить   
        '<<<прочее>>>
    'IF RG.fTEST_etap (array ("2020","","","")) THEN 
    '= otklonenie_seshen (nomer_sesh)   '  возвращает величину отклонения psech от  pmax   + превышение; - недобор
    '= Rastr.Calc("sum,max,min,val","area","qn","vibor") - функция (vibor не может быть "")
    ' ПОТРЕБЛЕНИЕ CorPotrNa(raion,potr, ZadSave) CorPotrTER(raion,potr, ZadSave)' територия CorOb(ob,potr, ZadSave)' обединение
    ' ГЕНЕРАТОРЫ call  PGen_cor ("sel")  'если мощность больше Pmax изменить мощность генератора  на Pmax, если меньше Pmin то на Pmin
    ' СЕЧЕНИЕ 'call KorSech (ns,newp,vibor) ' (ns,newp,vibor , tip, net_Pmin_zad) ' номер сеч, новая мощность в сеч (значение или "max" "min"), выбор корр узлов  (нр "sel"или "" - авто) ,  tip - pn или qn, net_Pmin_zad ' 1 не учитывать Pmin 
    ' call Qgen_node_in_gen_sub ()  ' посчитать Q ГЕН по  Q в узле        
        '<<<настройки rastr>>>
    ' Rastr.Tables("com_regim").Cols("gen_p").Z(0) = 0 '   0- "да"; 1- "да"; 2- только Р; 3- только Q ///it_max  количество расчетов///neb_p точность расчектов////
    
        '<<<ТКЗ>>>
    '   call Delet_node_VL_sub () ' удалить промежкточные точки на ЛЭП при отсутствии магнитной связи