# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt_calc_ur_set.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_calc_ur_set(object):
    def setupUi(self, calc_ur_set):
        calc_ur_set.setObjectName("calc_ur_set")
        calc_ur_set.resize(721, 116)
        self.centralwidget = QtWidgets.QWidget(calc_ur_set)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.cb_gost = QtWidgets.QCheckBox(self.centralwidget)
        self.cb_gost.setChecked(True)
        self.cb_gost.setObjectName("cb_gost")
        self.verticalLayout.addWidget(self.cb_gost)
        self.cb_skrm = QtWidgets.QCheckBox(self.centralwidget)
        self.cb_skrm.setChecked(True)
        self.cb_skrm.setObjectName("cb_skrm")
        self.verticalLayout.addWidget(self.cb_skrm)
        self.cb_avr = QtWidgets.QCheckBox(self.centralwidget)
        self.cb_avr.setChecked(True)
        self.cb_avr.setObjectName("cb_avr")
        self.verticalLayout.addWidget(self.cb_avr)
        self.b_save = QtWidgets.QPushButton(self.centralwidget)
        self.b_save.setObjectName("b_save")
        self.verticalLayout.addWidget(self.b_save)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        calc_ur_set.setCentralWidget(self.centralwidget)

        self.retranslateUi(calc_ur_set)
        QtCore.QMetaObject.connectSlotsByName(calc_ur_set)

    def retranslateUi(self, calc_ur_set):
        _translate = QtCore.QCoreApplication.translate
        calc_ur_set.setWindowTitle(_translate("calc_ur_set", "Настройки"))
        self.cb_gost.setText(_translate("calc_ur_set", "ГОСТ 58670-2019. Для зимы и ПЭВТ не учитывать PP и РРО. Не учитывать ограничение ДДТН и МДН: зима, ПЭВТ - РО, прочие - РРО"))
        self.cb_skrm.setText(_translate("calc_ur_set", "Функция включения/отключения СКРМ  "))
        self.cb_avr.setText(_translate("calc_ur_set", "АВР"))
        self.b_save.setText(_translate("calc_ur_set", "Соханить"))
