# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt_set.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Settings(object):
    def setupUi(self, Settings):
        Settings.setObjectName("Settings")
        Settings.resize(684, 204)
        self.widget = QtWidgets.QWidget(Settings)
        self.widget.setGeometry(QtCore.QRect(0, 2, 681, 193))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.LE_path = QtWidgets.QLineEdit(self.widget)
        self.LE_path.setObjectName("LE_path")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.LE_path)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.LE_rg2 = QtWidgets.QLineEdit(self.widget)
        self.LE_rg2.setObjectName("LE_rg2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.LE_rg2)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.LE_rst = QtWidgets.QLineEdit(self.widget)
        self.LE_rst.setObjectName("LE_rst")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.LE_rst)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.LE_sch = QtWidgets.QLineEdit(self.widget)
        self.LE_sch.setObjectName("LE_sch")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.LE_sch)
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.LE_amt = QtWidgets.QLineEdit(self.widget)
        self.LE_amt.setObjectName("LE_amt")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.LE_amt)
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.LE_trn = QtWidgets.QLineEdit(self.widget)
        self.LE_trn.setObjectName("LE_trn")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.LE_trn)
        self.verticalLayout.addLayout(self.formLayout)
        self.set_save = QtWidgets.QPushButton(self.widget)
        self.set_save.setObjectName("set_save")
        self.verticalLayout.addWidget(self.set_save)

        self.retranslateUi(Settings)
        QtCore.QMetaObject.connectSlotsByName(Settings)

    def retranslateUi(self, Settings):
        _translate = QtCore.QCoreApplication.translate
        Settings.setWindowTitle(_translate("Settings", "Настройки"))
        self.label.setText(_translate("Settings", "Путь к папке RastrWin3:"))
        self.LE_path.setText(_translate("Settings", "C:\\Users\\User\\Documents\\RastrWin3"))
        self.label_2.setText(_translate("Settings", "Шаблон .rg2:"))
        self.LE_rg2.setText(_translate("Settings", "C:\\Users\\User\\Documents\\RastrWin3\\SHABLON\\режим.rg2"))
        self.label_3.setText(_translate("Settings", "Шаблон .rst:"))
        self.LE_rst.setText(_translate("Settings", "C:\\Users\\User\\Documents\\RastrWin3\\SHABLON\\динамика.rst"))
        self.label_4.setText(_translate("Settings", "Шаблон .sch:"))
        self.LE_sch.setText(_translate("Settings", "C:\\Users\\User\\Documents\\RastrWin3\\SHABLON\\сечения.sch"))
        self.label_5.setText(_translate("Settings", "Шаблон .amt:"))
        self.LE_amt.setText(_translate("Settings", "C:\\Users\\User\\Documents\\RastrWin3\\SHABLON\\автоматика.amt"))
        self.label_6.setText(_translate("Settings", "Шаблон .trn:"))
        self.LE_trn.setText(_translate("Settings", "C:\\Users\\User\\Documents\\RastrWin3\\SHABLON\\трансформаторы.trn"))
        self.set_save.setText(_translate("Settings", "Соханить"))
