# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt_set.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Settings(object):
    def setupUi(self, Settings):
        Settings.setObjectName("Settings")
        Settings.resize(552, 230)
        self.groupBox = QtWidgets.QGroupBox(Settings)
        self.groupBox.setGeometry(QtCore.QRect(10, 0, 531, 181))
        self.groupBox.setObjectName("groupBox")
        self.widget = QtWidgets.QWidget(self.groupBox)
        self.widget.setGeometry(QtCore.QRect(20, 20, 501, 138))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.LE_shablon_rg2 = QtWidgets.QLineEdit(self.widget)
        self.LE_shablon_rg2.setObjectName("LE_shablon_rg2")
        self.verticalLayout.addWidget(self.LE_shablon_rg2)
        self.LE_shablon_rst = QtWidgets.QLineEdit(self.widget)
        self.LE_shablon_rst.setObjectName("LE_shablon_rst")
        self.verticalLayout.addWidget(self.LE_shablon_rst)
        self.LE_shablon_sch = QtWidgets.QLineEdit(self.widget)
        self.LE_shablon_sch.setObjectName("LE_shablon_sch")
        self.verticalLayout.addWidget(self.LE_shablon_sch)
        self.LE_shablon_trn = QtWidgets.QLineEdit(self.widget)
        self.LE_shablon_trn.setObjectName("LE_shablon_trn")
        self.verticalLayout.addWidget(self.LE_shablon_trn)
        self.LE_shablon_anc = QtWidgets.QLineEdit(self.widget)
        self.LE_shablon_anc.setObjectName("LE_shablon_anc")
        self.verticalLayout.addWidget(self.LE_shablon_anc)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.CB_load_trn_anc = QtWidgets.QCheckBox(self.groupBox)
        self.CB_load_trn_anc.setGeometry(QtCore.QRect(20, 160, 491, 19))
        self.CB_load_trn_anc.setChecked(True)
        self.CB_load_trn_anc.setObjectName("CB_load_trn_anc")
        self.PB_qt_set_save = QtWidgets.QPushButton(Settings)
        self.PB_qt_set_save.setGeometry(QtCore.QRect(20, 190, 511, 21))
        self.PB_qt_set_save.setStyleSheet("")
        self.PB_qt_set_save.setObjectName("PB_qt_set_save")

        self.retranslateUi(Settings)
        QtCore.QMetaObject.connectSlotsByName(Settings)

    def retranslateUi(self, Settings):
        _translate = QtCore.QCoreApplication.translate
        Settings.setWindowTitle(_translate("Settings", "Настройки программы"))
        self.groupBox.setTitle(_translate("Settings", "Шаблоны"))
        self.label_2.setText(_translate("Settings", "Шаблон .rg2:"))
        self.label_3.setText(_translate("Settings", "Шаблон .rst:"))
        self.label_4.setText(_translate("Settings", "Шаблон .sch:"))
        self.label_5.setText(_translate("Settings", "Шаблон .trn:"))
        self.label.setText(_translate("Settings", "Шаблон .anc:"))
        self.LE_shablon_rg2.setText(_translate("Settings", "C:\\Users\\User\\Documents\\RastrWin3\\SHABLON\\режим.rg2"))
        self.LE_shablon_rst.setText(_translate("Settings", "C:\\Users\\User\\Documents\\RastrWin3\\SHABLON\\динамика.rst"))
        self.LE_shablon_sch.setText(_translate("Settings", "C:\\Users\\User\\Documents\\RastrWin3\\SHABLON\\сечения.sch"))
        self.LE_shablon_trn.setText(_translate("Settings", "C:\\Users\\User\\Documents\\RastrWin3\\SHABLON\\трансформаторы.trn"))
        self.LE_shablon_anc.setText(_translate("Settings", "C:\\Users\\User\\Documents\\RastrWin3\\SHABLON\\анцапфы.anc"))
        self.CB_load_trn_anc.setText(_translate("Settings", "При загрузке файла rst или rg2 загружать одноименные файлы trn и anc (из той же папки)"))
        self.PB_qt_set_save.setText(_translate("Settings", "Соханить"))
