# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt_choice.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_choice(object):
    def setupUi(self, choice):
        choice.setObjectName("choice")
        choice.setEnabled(True)
        choice.resize(423, 205)
        self.centralwidget = QtWidgets.QWidget(choice)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.correction = QtWidgets.QPushButton(self.centralwidget)
        self.correction.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.correction.setFont(font)
        self.correction.setObjectName("correction")
        self.gridLayout.addWidget(self.correction, 1, 0, 1, 1)
        self.calc_ur = QtWidgets.QPushButton(self.centralwidget)
        self.calc_ur.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.calc_ur.setFont(font)
        self.calc_ur.setObjectName("calc_ur")
        self.gridLayout.addWidget(self.calc_ur, 2, 0, 1, 1)
        self.settings = QtWidgets.QPushButton(self.centralwidget)
        self.settings.setMinimumSize(QtCore.QSize(0, 40))
        self.settings.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.settings.setFont(font)
        self.settings.setToolTip("")
        self.settings.setObjectName("settings")
        self.gridLayout.addWidget(self.settings, 3, 0, 1, 1)
        choice.setCentralWidget(self.centralwidget)

        self.retranslateUi(choice)
        QtCore.QMetaObject.connectSlotsByName(choice)

    def retranslateUi(self, choice):
        _translate = QtCore.QCoreApplication.translate
        choice.setWindowTitle(_translate("choice", "Программа автоматизации работы с RastrWin3"))
        self.correction.setText(_translate("choice", "Изменение моделей"))
        self.calc_ur.setText(_translate("choice", "Расчет установившихся режимов"))
        self.settings.setText(_translate("choice", "Настройки"))
